### ISSUE TITLE
L0 Loss?

### ISSUE THREAD

**Issue by jbshao** [yu4u/noise2noise#16]
Thanks so much for your implementation.

However I noticed that there is no annealed L0 loss implemented in this current version. Do you plan to update to include this in the future? Especially I notice that L0 showed much better performances in some of the tasks from the original paper.

**Comment by yu4u** [comment]
Thank you for your suggestion.
I'll try later.

**Comment by yu4u** [comment]
Random-valued impulse noise model and L0 loss were now implemented!

**Comment by jbshao** [comment]
This is great, thanks so much!
