### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by victorca25** [yu4u/noise2noise#34]
Any recommendation to handle OOM problems?

I'm using tensorflow with GPU (GTX 1060 6GB) and it dies fairly quickly with higher resolutions. I know in some cases dividing the images into slices and stitching them back together works, but I don't know if in this case that's an option.

**Comment by yu4u** [comment]
Yes, decreasing batch_size or image_size reduces memory requirement, and it would work to some extent.

**Comment by CyberLykan** [comment]
> Yes, decreasing batch_size or image_size reduces memory requirement, and it would work to some extent.

How would you change the batch_size

**Comment by yu4u** [comment]
Please see readme.
