### ISSUE TITLE
How do I use the trained model file to remove noise from my photos?

### ISSUE THREAD

**Issue by ghost** [yu4u/noise2noise#42]
I use this command.
`!python3 test_model.py --weight_file clean.hdf5  --image_dir cleanimage --output_dir Resdir`
But it won't export the original size image.

It generates three image combinations.

What should I do to export the noise-reduced image and keep the original size?

**Comment by yu4u** [comment]
You can modify the code to save denoised images.

https://github.com/yu4u/noise2noise/blob/master/test_model.py#L54
