### ISSUE TITLE
How to modify random text noise for custom image noise?

### ISSUE THREAD

**Issue by ghost** [yu4u/noise2noise#43]
I am going to train the image to remove the watermark.
I have some transparent watermark images now.
what should I do?
How should I change the random text overlay to a custom watermark overlay?

**Comment by yu4u** [comment]
This repo is not suitable for this kind of purposes.
The main purpose of this repo is to reproduce the idea of noise2noise training, not to create useful denoising models.
There should be more suitable denoising implementations other than this repo.
